# Generated by Django 5.2.4 on 2025-07-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('SEA', 'Smart Energy Assessment'), ('CSE', 'Custom Solar & Efficiency Plan'), ('SER', 'Sustainability & ESG Roadmap'), ('REC', 'Remote Energy Coaching'), ('IS', 'Installation & Supervision')], max_length=3, unique=True),
        ),
    ]
