# Generated by Django 5.2.4 on 2025-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0002_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.CharField(choices=[('SEA', 'Smart Energy Assessment'), ('CSE', 'Custom Solar & Efficiency Plan'), ('SER', 'Sustainability & ESG Roadmap'), ('REC', 'Remote Energy Coaching'), ('IS', 'Installation & Supervision'), ('OTH', 'Other')], max_length=3),
        ),
    ]
