# Generated by Django 5.2.4 on 2025-07-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0003_alter_servicerequest_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESGResource',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
