# Generated by Django 5.2.4 on 2025-07-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0004_delete_esgresource_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-31 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-31 00:00:00'),
            preserve_default=False,
        ),
    ]
